<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PizzaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

// 1) Root (/) route -> homepage
Route::get('/', function () {
    return view('homepage');
});

// 2) Dashboard (requires auth, verified email)
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// 3) Auth routes for user profile
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// 4) Openingstijden page
Route::get('/openingstijden', function () {
    return view('openingstijden');
})->name('openingstijden');

// 5) /home route -> homepage
Route::get('/home', function () {
    return view('homepage');
})->name('home');

/*
|--------------------------------------------------------------------------
| Pizza Routes
|--------------------------------------------------------------------------
|
| These routes handle displaying pizzas, adding to cart, updating cart,
| and removing items from cart.
|
*/

Route::get('/pizza', [PizzaController::class, 'index'])->name('pizza.index');
Route::post('/pizza/add-to-cart/{id}', [PizzaController::class, 'addToCart'])->name('pizza.addToCart');

// For updating item quantity in cart
Route::post('/pizza/update-cart/{id}', [PizzaController::class, 'updateCart'])->name('pizza.updateCart');

// For removing an item from the cart
Route::delete('/pizza/remove-from-cart/{id}', [PizzaController::class, 'removeFromCart'])->name('pizza.removeFromCart');

// Include auth routes generated by Laravel (e.g., login, register, etc.)
require __DIR__ . '/auth.php';
